### ISSUE TITLE
can't install 

### ISSUE THREAD

**Issue by soitun** [marellocommerce/marello-application#6]
> install-assets: Oro\Bundle\InstallerBundle\Composer\ScriptHandler::installAssets
Script Oro\Bundle\InstallerBundle\Composer\ScriptHandler::installAssets handling the install-assets event terminated with an exception

                                                                                                               
  [Symfony\Component\Filesystem\Exception\IOException]                                                         
  Failed to create symbolic link from "../moment.js" to "public/bundles/bowerassets/moment/meteor/moment.js". 

-----------------------------------
ubuntu 16.0.4
nodejs : v6.14.4
php : 7.2.3

**Comment by 24198** [comment]
Hi @soitun,

Could you please list your steps from cloning to install, this will help debugging the issue. We've tested the setup we're currently running and are not able to reproduce the error.
Our current setup is with:
Marello CE version: 2.1
OS version: 16.04.4 LTS
Nodejs version: v6.16.0
PHP version: 7.2.16

Could you please describe which Marello version you've cloned and what steps you've taken in order to install the application?

Kind Regards,


Jaimy Casteleijn

**Comment by soitun** [comment]
thanks for help
